### PR TITLE
Remove need for non-standard SIZEOF

### LINKED ISSUE #77: Failure to compile SIZEOF (NAG) in suleg_mod
NAG compiles are failing in suleg_mod like this:

Error: /home/h01/frwd/cylc-run/mi-be984/work/1/ecbuild_ectrans_nag/build/src/trans/generated/ectrans_dp/internal/suleg_mod.F90, line 1207: Implicit type for SIZEOF in SULEG
[NAG Fortran Compiler pass 1 error termination, 1 error]
Error: /home/h01/frwd/cylc-run/mi-be984/work/1/ecbuild_ectrans_nag/build/src/trans/generated/ectrans_sp/internal/suleg_mod.F90, line 1207: Implicit type for SIZEOF in SULEG
[NAG Fortran Compiler pass 1 error termination, 1 error]

### PR DESCRIPTION
**Pull request by samhatfield**
Builds on #78 and resolves #77.

I remove one redundant `IF` statement (right above there is logic which ensures the condition is always `.TRUE.`.

I also remove the `SIZEOF` by simply checking the value of the integer used to determine the size of the allocated array, rather than checking how many bytes were actually allocated.

### CODE REVIEW

File: src/trans/internal/suleg_mod.F90 [hunk 1]
```diff
@@ -874,10 +871,9 @@ SUBROUTINE SULEG
                 ZCLONEA(IMLOC)%COMMSBUF(1:ICLONELEN) = ZRCVBUTFV(1:ICLONELEN,JSETV)
                 CALL UNPACK_BUTTERFLY_STRUCT(S%FA(IMLOC)%YBUT_STRUCT_A,ZCLONEA(IMLOC))
               ENDIF
-              IF(ALLOCATED(ZCLONEA(IMLOC)%COMMSBUF) ) THEN
-                IF( SIZEOF(ZCLONEA(IMLOC)%COMMSBUF) > 0 ) DEALLOCATE(ZCLONEA(IMLOC)%COMMSBUF)
-                !              ZCLONEA(IMLOC)%COMMSBUF=>NULL()
-              ENDIF
+
+              IF( ICLONELEN > 0 ) DEALLOCATE(ZCLONEA(IMLOC)%COMMSBUF)
+
```
Comment (wdeconinck) [inline src/trans/internal/suleg_mod.F90:876]: I think that ICLONELEN could be unininitialized in case
`IF( .NOT.ALLOCATED(ZCLONEA(IMLOC)%COMMSBUF) )THEN` (line 868) is not triggered.
Probably the `IF(ALLOCATED(ZCLONEA(IMLOC)%COMMSBUF) ) THEN` was still correct.
Could it not also be that it needs to stay allocated across iterations? Otherwise why all the guards (line 868).

File: src/trans/internal/suleg_mod.F90 [hunk 2]
```diff
@@ -1157,10 +1153,9 @@ SUBROUTINE SULEG
                 ZCLONES(IMLOC)%COMMSBUF(1:ICLONELEN) = ZRCVBUTFV(1:ICLONELEN,JSETV)
                 CALL UNPACK_BUTTERFLY_STRUCT( S%FA(IMLOC)%YBUT_STRUCT_S,ZCLONES(IMLOC))
               ENDIF
-              IF( ALLOCATED(ZCLONES(IMLOC)%COMMSBUF) ) THEN
-                IF( SIZEOF(ZCLONES(IMLOC)%COMMSBUF) > 0 ) DEALLOCATE(ZCLONES(IMLOC)%COMMSBUF)
-                !              ZCLONES(IMLOC)%COMMSBUF=>NULL()
-              ENDIF
+
+              IF( ICLONELEN > 0 ) DEALLOCATE(ZCLONES(IMLOC)%COMMSBUF)
```
Comment (DJDavies2) [inline src/trans/internal/suleg_mod.F90:1157]: Ditto

**Comment by DJDavies2** [comment]
I've tested here and it seems to work for me.

File: src/trans/internal/suleg_mod.F90 (hunk 1 above)
Comment (samhatfield) [reply src/trans/internal/suleg_mod.F90:876]: Good point @wdeconinck - we shouldn't use `ICLONELEN`.

The first `IF` has no purpose at all, as far as I can see. I can't see how it's possible for `ZCLONEA(IMLOC)%COMMSBUF` to not be allocated at line 877.

Instead of checking if `ICLONELEN > 0`, why don't we check `STORAGE_SIZE(ZCLONEA(IMLOC)%COMMSBUF) > 0`? `STORAGE_SIZE` is the same as `SIZEOF` but returns the bits allocated rather than bytes, and it appears to be part of the Fortran 2008 standard, unlike `SIZEOF`.

**Comment by samhatfield** [comment]
@DJDavies2 - could you test the latest commit with NAG Fortran?

**Comment by DJDavies2** [comment]
This branch seems to work for me as far as it goes.

**Comment by DJDavies2** [comment]
I'm down as a reviewer for this but I don't think I have the permissions to do that?  I am happy to "approve" this.

**Review by wdeconinck — APPROVED** [review]
OK for me. Nice cleanup
